---
version: 0.2
env:
  variables:
    ProjectPath: "./Profile.Service"
    ProjectFilePath: "./Profile.Service/Profile.Service.csproj"
    Configuration: "Release"
    PublishDir: "Publish_Output"
phases:
    install:
      runtime-versions:
        docker: 18
        dotnet: 3.0
    pre_build:
      commands:
        - echo Restore started on `date`
        - dotnet restore $ProjectFilePath
        - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
        - REPOSITORY_URI=829274941445.dkr.ecr.us-east-1.amazonaws.com/profile-svc
    build:
      commands:
        - echo Build started on `date`
        - SHA=$(git rev-parse --short HEAD)
        - VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" $ProjectFilePath)
        - pwd
        - dotnet publish $ProjectFilePath -c $Configuration -o ./$PublishDir
        - pwd 
        - cd $PublishDir
        - ls
        - cd ..
        - pwd 
        - ImageRepoName=${CODEBUILD_BUILD_ID%:*}
        - docker build $ProjectPath -f $ProjectPath/Dockerfile -t $REPOSITORY_URI/$ImageRepoName:$VERSION-$SHA
        - docker push $REPOSITORY_URI:$VERSION-$SHA
        - echo Build completed on `date`